Reward and contribution models
AndrewStearns2018/training-project pull request #13
Opened 2019-09-30 12:03 UTC by AndrewStearns2018

Je n'ai pas créé de tests pour les modèles, parce que les validations sont simples.

2019-09-30 14:19 UTC, Kernael requested changes

2019-09-30 14:19 UTC, Kernael commented on app/models/contribution.rb
> +  validates :amount, presence: true, numericality: { only_integer: false }
`amount` ne devrait-il pas être un `integer` en tout circonstance ?

2019-09-30 14:19 UTC, Kernael commented on app/models/reward.rb
> +  has_many :contributions
n'oublie pas l'option `:dependent`

2019-09-30 14:19 UTC, Kernael commented on db/seeds.rb
> +Reward.destroy_all
my bad si je n'ai pas remarqué ça avant : 

en général il est préférable que le fichier de seed ne se préoccupe pas de détruire des ressources, mais uniquement d'en créer

2019-09-30 15:50 UTC, AndrewStearns2018 commented on app/models/contribution.rb
> +  validates :amount, presence: true, numericality: { only_integer: false }
Je pensais mettre en place une logique où le prix d'une contrepartie pour être 19,99 pour des raisons de marketing et où l'utilisateur pourrait ainsi créer une contribution d'un montant au centime près. Si tu penses que cela ne vaut pas la peine, je changerai.

2019-09-30 15:50 UTC, AndrewStearns2018 commented on app/models/reward.rb
> +  has_many :contributions
J'ai ajouté cette logique dans un commit sur une autre branche.

2019-09-30 15:54 UTC, Kernael commented on app/models/contribution.rb
> +  validates :amount, presence: true, numericality: { only_integer: false }
Non pas de soucis ! Mais dans ce cas il y a deux choses : 

- Il faut que `amount` soit du type `decimal` en base de données
- Il faut quand même avoir une validation de type `numericality: { greather_than: ... }`

Comme tu préfères ! Soit tu part sur un `integer`, soit un `decimal` mais pas "l'entre-deux" ^^

2019-10-01 10:00 UTC, AndrewStearns2018 commented on app/models/contribution.rb
> +  validates :amount, presence: true, numericality: { only_integer: false }
J'ai changé en entier et inclus la logique > 0. 

Je vais modifier les validations du modèle Reward de la même façon.

2019-10-03 11:51 UTC, AndrewStearns2018 commented on db/seeds.rb
> +Reward.destroy_all
J'ai voulu éviter les problèmes de 'uniqueness' si je voulais refaire le seed.

2019-10-03 12:34 UTC, Kernael commented on db/seeds.rb
> +Reward.destroy_all
Yes je me doute bien ^^ mais c'est vraiment un coup à se tromper car on ne s'attend pas à ce que les seeds détruisent des ressources

2019-10-04 09:12 UTC, closed without merging