Contribution can buy a certain number of units based on price and ava…
AndrewStearns2018/training-project pull request #30
Opened 2019-10-04 09:07 UTC by AndrewStearns2018

…ilibility. Reward is optional

2019-10-10 13:50 UTC, Kernael requested changes

2019-10-10 13:50 UTC, Kernael commented on app/views/contributions/new.html.erb
> +    |reward| "#{reward.name} - #{reward.price} €" },:value_method => :id,:label => "Reward" ,:include_blank => true %>
je n'ai jamais utilisé `label_method` et `value_method`, à quoi te servent-ils ici ?
je pense que tu peux simplement utiiser `value` et `label`

2019-10-10 13:50 UTC, Kernael commented on app/transactions/create_contribution_transaction.rb
> +      @reward = Reward.find(@contribution[:reward_id])
`@contribution.reward`

2019-10-10 13:50 UTC, Kernael commented on app/controllers/contributions_controller.rb
> +    end
tu peux faire ça dans la transaction

2019-10-10 13:50 UTC, Kernael commented on app/controllers/contributions_controller.rb
> +        @project = Project.find(params[:project_id])
Tu devrais pouvoir faire les choses de façon à ne pas avoir besoin de faire ça

Par exemple, le faire en tout premier, puis passer `@project` à ta transaction

De plus, c'est bizarre de faire `@contribution = Contribution.new` parce-que ça veut dire que tu perds les erreurs que tu voudrais afficher les utilisateurs

2019-10-11 09:45 UTC, AndrewStearns2018 commented on app/controllers/contributions_controller.rb
> +    end
J'ai fait comme ça, parce que je voulais avoir permitted: true en passant par les contribution_params. Je ne peux pas faire un merge avec des paramètres autorisés et des paramètres non autorisés. 

Comment faire pour avoir accès aux paramètres de base comme project_id et les strong params qui m'autoriseront à créer une contribution ?

2019-10-11 12:19 UTC, AndrewStearns2018 commented on app/views/contributions/new.html.erb
> +    |reward| "#{reward.name} - #{reward.price} €" },:value_method => :id,:label => "Reward" ,:include_blank => true %>
Label_method semble permettre l'emploi d'un lambda, ce qui me permet d'afficher le nom et le prix d'une contrepartie.

2019-10-11 12:41 UTC, Kernael commented on app/views/contributions/new.html.erb
> +    |reward| "#{reward.name} - #{reward.price} €" },:value_method => :id,:label => "Reward" ,:include_blank => true %>
Yes mais il te suffit de faire `label: "#{reward.name} - #{reward.price} €"`

2019-10-11 12:43 UTC, closed without merging